# Default values for your projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: dev
#this replicaCount is needed if hpa is not enabled
replicaCount: 1
image:
  repository: sample-java
  tag: "latest"
  pullPolicy: IfNotPresent
# optional list of image pull secrets to use to pull images

amnic:
  revision: revisionId
  runtimeVersion: v0.0.4
  # optional image pull secrets
  imagePullSecrets: []
  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: false
# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80
service:
  enabled: true
  name: javasample
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
ingress:
  internal:
    host: minerva.dev.internal.amniclhs.com
  external:
    host: minerva.dev.amniclhs.com
istio:
  virtualService:
    internal:
      enabled: true
      paths:
        - name: ""
    external:
      enabled: true
      paths:
        - name: ""
rollout:
  # Used for all three strategies
  progressDeadlineSeconds: 0
  revisionHistoryLimit: 0
  minReadySeconds: 0
  # Used for canary and blue_green strategy
  progressDeadlineAbort: false
  # This takes affect only when traffic routing is enabled
  scaleDownDelaySeconds: 30
  # scaleDownDelayRevisionLimit can't be greater than revisionHistoryLimit
  scaleDownDelayRevisionLimit: 10
  abortScaleDownDelaySeconds: 30
  # Accepted values: canary, blue_green, rolling
  strategy: rolling
  # Canary strategy configs
  canary:
    # Can't be 0 when maxSurgePercentage is 0
    maxUnavailable: 0
    # Can't be 0 when maxUnavailable is 0
    maxSurgePercentage: 20
    # Accepted values: host_level, subset_level
    trafficSplitting: host_level
    steps:
      - key: setWeight
        value: 50
      - key: setCanaryScale
        value: {"weight": 50}
      - key: pause
        value: {}
  # Blue-green strategy configs
  blueGreen:
    previewReplicaCount: 1
    autoPromotionEnabled: false
    autoPromotionSeconds: 300
  # Rolling strategy configs
  rolling:
    maxUnavailable: 0
    maxSurgePercentage: 0%
resources:
  limits:
    cpu: 400m
    memory: 1000M
  requests:
    cpu: 400m
    memory: 1000M
# default spring boot probe path
probePath: /health/ping
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: "/health/ping"
readinessProbe:
  failureThreshold: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: "/health/ping"
serviceAccount:
  enabled: true
  annotations: null
  #eks.amazonaws.com/role-arn: arn:aws:iam::848288613192:role/dev-runtime-nonprod-cluster-amnic-k8s-irsa-role
  labels: {}
#    my-custom-label: value
secrets:
  enabled: false
  config:
    annotations:
      amnicRuntimeVersion: v0.0.3
      updatedAt: Fri Sep  2 13:26:16 IST 2022
config:
  disabled: false
env:
  TEST_INT_VALUE: 2
  TEST_MAP_VALUE: 
    key1: value1
    key2: value2
    key3: value3
  TEST_BOOL_VALUE: true

